cp .gitconfig ~/
cp .inputrc ~/
cp .psqlrc ~/
cp .tmux.conf ~/
cp .zshrc ~/
cp .custom.zsh-theme ~/.oh-my-zsh/themes/custom.zsh-theme
cp .alias ~/
cp .fzf_functions ~/
cp init.vim ~/.config/nvim/init.vim
